---
  - name: set_interface_mikrotik
    community.routeros.command:
      commands:
        -  /ip address add address={{ item.ipv4_address }} interface={{ item.interface }}
    loop: "{{ interfaces }}"
    loop_control:
      label: "{{ item.interface }}"
    tags: set_interface

  - name: configure_bgp
    community.routeros.command:
      commands:
        - /routing bgp connection add address-families=ip as={{ bgp.as }} local.address={{ bgp.router_id }} .role=ibgp name={{ item.description }} nexthop-choice=force-self output.default-originate=if-installed remote.address={{ item.ipv4_address }} .as={{ item.remote_as }} router-id={{ bgp.router_id }} routing-table=main
    loop: "{{ bgp.neighbors }}"
    loop_control:
      label: "{{ item.ipv4_address }}"
