router:
  vars:
    ansible_user: vyos
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: vyos.vyos.vyos
    
    aibix_pubkey: 'AAAAB3NzaC1yc2EAAAADAQABAAABgQCPWJdrzcquOHSts5KPhbP0NZf5gczoZL20o/a4gd6kI3DlgSBBS0fRsoCryhYf31nH978jCQL009SFanBkVXoZFGGZ9GfaPLdCBq4hbeF3upDBFLbL3kIc5rnv6NRzN5P2pfa5DTLGCvrK+kA4vNlHk5dYjH8NlgHC6Yr9ldLFBucbmIhbE+zt43qY+DuXOQYW9LFpYSO/91QRqW9Y3AqqnPOD4tXLlOsorKa2KFoQO7F25BGx4a5vp3Yg1oYlaTzCJzjOELzBNQ8LnH4i11PN/+rT0S1B5kg8nNJNljvxX705Nzg/2bDwd9vbxOgL0tUP/gkppNs2Y4gJ3G/gXWs/jSu8mt2hqt+Gf3AWl2v5AI9Dr6Jj3iTIAtg7kJTiIlhZLZVY7Iq2C6JzviMFq6T9jnHrLDA MkDiajHZcw3CNt/jayNKi5jD9uSggEOl4OGDMClnN6V/txXJTZjbYmd+fbIkNTQv9vIn9e0ThKbsP/lStH5dfNVaDZo6gbhmee0='
    aibix_pubkey_id: aibix@hel
    aibix_pubkey_type: 'ssh-rsa'
    

  hosts:
    r1v:
      os: "vyos"
      ansible_host: 10.20.30.1

      interfaces:
        - interface: lo
          interface_type: loopback
          ipv4_address: 10.10.255.1/32

        - interface: eth0
          interface_type: ethernet
          ipv4_address: dhcp
          hw_address: 00:50:56:01:0e:cc

        - interface: eth1
          interface_type: ethernet
          ipv4_address: 10.10.15.1/24

        - interface: eth2
          interface_type: ethernet
          ipv4_address: 10.10.12.1/24

        - interface: eth4
          interface_type: ethernet
          ipv4_address: 10.1.11.1/24

      ospf_network:
        - 10.10.12.0/24
        - 10.10.15.0/24
        - 10.10.255.1/32
      ospf_interface:
        - eth1
        - eth2


    r2v:
      os: "vyos"
      ansible_host: 10.20.30.2

      interfaces:
        - interface: lo
          interface_type: loopback
          ipv4_address: 10.10.255.2/32

        - interface: eth0
          interface_type: ethernet
          ipv4_address: 10.10.12.2/24

        - interface: eth1
          interface_type: ethernet
          ipv4_address: 10.10.26.2/24

        - interface: eth2
          interface_type: ethernet
          ipv4_address: 10.10.23.2/24

        - interface: eth4
          interface_type: ethernet
          ipv4_address: 10.2.12.2/24

      ospf_network:
        - 10.10.12.0/24
        - 10.10.23.0/24
        - 10.10.26.0/24
        - 10.10.255.2/32
      ospf_interface:
        - eth0
        - eth1
        - eth2


    r3v:
      os: "vyos"
      ansible_host: 10.20.30.3

      interfaces:
        - interface: lo
          interface_type: loopback
          ipv4_address: 10.10.255.3/32

        - interface: eth0
          interface_type: ethernet
          ipv4_address: 10.10.23.3/24

        - interface: eth1
          interface_type: ethernet
          ipv4_address: 10.10.37.3/24

        - interface: eth2
          interface_type: ethernet
          ipv4_address: 10.10.34.3/24

      ospf_network:
        - 10.10.23.0/24
        - 10.10.34.0/24
        - 10.10.37.0/24
        - 10.10.255.3/32
      ospf_interface:
        - eth0
        - eth1
        - eth2



    r4v:
      os: "vyos"
      ansible_host: 10.20.30.4

      interfaces:
        - interface: lo
          interface_type: loopback
          ipv4_address: 10.10.255.3/32

        - interface: eth0
          interface_type: ethernet
          ipv4_address: 10.10.34.4/24

        - interface: eth1
          interface_type: ethernet
          ipv4_address: 10.10.48.4/24

        - interface: eth2
          interface_type: ethernet
          ipv4_address: 172.16.4.1/24

      ospf_network:
        - 10.10.34.0/24
        - 10.10.48.0/24
        - 10.10.255.4/32
        - 172.16.4.0/24
      ospf_interface:
        - eth0
        - eth1


    r5v:
      os: "vyos"
      ansible_host: 10.20.30.5

      interfaces:
        - interface: lo
          interface_type: loopback
          ipv4_address: 10.10.255.5/32

        - interface: eth0
          interface_type: ethernet
          ipv4_address: 172.16.5.1/24

        - interface: eth1
          interface_type: ethernet
          ipv4_address: 10.10.15.5/24

        - interface: eth2
          interface_type: ethernet
          ipv4_address: 10.10.56.5/24

      ospf_network:
        - 10.10.15.0/24
        - 10.10.56.0/24
        - 10.10.255.5/32
        - 172.16.5.0/24
      ospf_interface:
        - eth1
        - eth2


    r6v:
      os: "vyos"
      ansible_host: 10.20.30.6

      interfaces:
        - interface: lo
          interface_type: loopback
          ipv4_address: 10.10.255.6/32

        - interface: eth0
          interface_type: ethernet
          ipv4_address: 10.10.56.6/24

        - interface: eth1
          interface_type: ethernet
          ipv4_address: 10.10.26.6/24

        - interface: eth2
          interface_type: ethernet
          ipv4_address: 10.10.67.6/24

      ospf_network:
        - 10.10.26.0/24
        - 10.10.56.0/24
        - 10.10.67.0/24
        - 10.10.255.6/32
      ospf_interface:
        - eth0
        - eth1
        - eth2

    r7v:
      os: "vyos"
      ansible_host: 10.20.30.7

      interfaces:
        - interface: lo
          interface_type: loopback
          ipv4_address: 10.10.255.7/32

        - interface: eth0
          interface_type: ethernet
          ipv4_address: 10.10.67.7/24

        - interface: eth1
          interface_type: ethernet
          ipv4_address: 10.10.37.7/24

        - interface: eth2
          interface_type: ethernet
          ipv4_address: 10.10.78.7/24

      ospf_network:
        - 10.10.37.0/24
        - 10.10.67.0/24
        - 10.10.78.0/24
        - 10.10.255.7/32
      ospf_interface:
        - eth0
        - eth1
        - eth2


    r8v:
      os: "vyos"
      ansible_host: 10.20.30.8

      interfaces:
        - interface: lo
          interface_type: loopback
          ipv4_address: 10.10.255.8/32

        - interface: eth0
          interface_type: ethernet
          ipv4_address: 10.10.78.8/24

        - interface: eth1
          interface_type: ethernet
          ipv4_address: 10.10.48.8/24

        - interface: eth2
          interface_type: ethernet
          ipv4_address: 172.16.8.1/24

      ospf_network:
        - 10.10.48.0/24
        - 10.10.78.0/24
        - 10.10.255.8/32
        - 172.16.8.0/24
      ospf_interface:
        - eth0
        - eth1
