---
mikrotik:
  vars:
    aibix_pubkey: 'AAAAB3NzaC1yc2EAAAADAQABAAABgQCPWJdrzcquOHSts5KPhbP0NZf5gczoZL20o/a4gd6kI3DlgSBBS0fRsoCryhYf31nH978jCQL009SFanBkVXoZFGGZ9GfaPLdCBq4hbeF3upDBFLbL3kIc5rnv6NRzN5P2pfa5DTLGCvrK+kA4vNlHk5dYjH8NlgHC6Yr9ldLFBucbmIhbE+zt43qY+DuXOQYW9LFpYSO/91QRqW9Y3AqqnPOD4tXLlOsorKa2KFoQO7F25BGx4a5vp3Yg1oYlaTzCJzjOELzBNQ8LnH4i11PN/+rT0S1B5kg8nNJNljvxX705Nzg/2bDwd9vbxOgL0tUP/gkppNs2Y4gJ3G/gXWs/jSu8mt2hqt+Gf3AWl2v5AI9Dr6Jj3iTIAtg7kJTiIlhZLZVY7Iq2C6JzviMFq6T9jnHrLDA MkDiajHZcw3CNt/jayNKi5jD9uSggEOl4OGDMClnN6V/txXJTZjbYmd+fbIkNTQv9vIn9e0ThKbsP/lStH5dfNVaDZo6gbhmee0='
    aibix_pubkey_id: aibix@hel
    aibix_pubkey_type: 'ssh-rsa'
    

  hosts:
    r11m:
      os: "mikrotik"
      ansible_host: 10.20.30.11

      interfaces:
        - interface: lo
          interface_type: loopback
          ipv4_address: 10.10.255.11/32

        - interface: WAN
          interface_type: ethernet
          ipv4_address: dhcp
          hw_address: 00:50:56:00:BE:28

        - interface: r1v
          interface_type: ethernet
          ipv4_address: 10.1.11.11/24

        - interface: r12m
          interface_type: ethernet
          ipv4_address: 10.11.12.11/24

      ospf_network:
        - 10.1.11.0/24
        - 10.11.12.0/24
        - 10.10.255.11/32
      ospf_interface:
        - ether2
        - ether3
        - lo


    r12m:
      os: "mikrotik"
      ansible_host: 10.20.30.12

      interfaces:
        - interface: lo
          interface_type: loopback
          ipv4_address: 10.10.255.12/32

        - interface: r11m
          interface_type: ethernet
          ipv4_address: 10.11.12.12/24

        - interface: r2v
          interface_type: ethernet
          ipv4_address: 10.2.12.12/24

        - interface: r13m
          interface_type: ethernet
          ipv4_address: 10.11.13.12/24

      ospf_network:
        - 10.2.12.0/24
        - 10.11.12.0/24
        - 10.10.255.12/32
      ospf_interface:
        - ether1
        - ether2
        - lo


