---

- hosts: router

  connection: network_cli
  gather_facts: 'no'

  tasks:
    - name: loopbacks
      vyos_config:
        lines:
          - set interfaces loopback lo address 10.10.255.{{ inventory_hostname[1:2] }}/32
        save: true
        
