---
- name: Vyos Kram
  hosts: router
  # throttle: 1
  gather_facts: no

  tasks:
  - name: configurable backup path
    vyos_config:
      backup: yes
      backup_options:
        filename: "{{ inventory_hostname }}"
        dir_path: "/home/aibix/lnr/ansible_out"

- name: git push
  hosts: localhost
  collections:
    - lvrfrc87.git_acp

  tasks:
  - name: push to github
    # run_once: true
    git_acp:
      path: "/home/aibix/lnr"
      add: [ "." ]
      branch: main
      comment: "auto-run: {{ now() }}"
      url: "git@github.com:aibix0001/lnr.git"
