---
- name: Vyos Kram
  hosts: router
  gather_facts: no
  collections:
    - lvrfrc87.git_acp

  tasks:
  - name: configurable backup path
    vyos_config:
      backup: yes
      backup_options:
        filename: "{{ inventory_hostname }}"
        dir_path: "/home/aibix/lnr/ansible_out"

  - name: push to github
    throttle: 1
    git_acp:
      path: "/home/aibix/lnr"
      add: [ "." ]
      branch: main
      comment: "auto-run: {{ now() }}"
      url: "git@github.com:aibix0001/lnr.git"
